db:
  driver: "org.postgresql.Driver"
  url: "postgres:5432"
  username: "postgres"
  password: "postgres"
  pool:
    size: 10
    timeout: 20
  pools:
    - size: 10
      timeout: 20
    - size: 15
      timeout: 30
  properties:
    key: "value"
    boy: "next door"
    randNum: 543

logging:
  level:
    root: WARN
    com.github.kalilina.spring.database: INFO
  file:
    name: ./logs/app.log
#    path: ./logs

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_starter
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

app:
  image:
    bucket: /home/bob/IdeaProjects/spring-starter/images